language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
install:
  - npm install
before_deploy:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  on:
    branch: master
